### PR TITLE
Update test data

### PR DESCRIPTION
**Pull request by mrezentes**
Successful test run completed.

### CODE REVIEW

**Comment by Envek** [comment]
Could you please explain why this change required?

**Comment by mrezentes** [comment]
Sorry for not including this in the original PR.
I pulled the repo and ran the tests. The `Signer should digest and sign SOAP XML with security node and digested binary token` test failed. Upon comparing the expected output with the actual output, there was a slight difference.

This commit brings the expected and actual into alignment. Tests now pass. 
Thanks.

**Comment by Envek** [comment]
What Ruby version you're using?

I can see that last commit in `master` branch have passed the build, but a pretty long time ago.

Will investigate in a few days. Thank you for PR.

**Comment by mrezentes** [comment]
I am using ruby 2.1.5p273

Thank you for your work in this repo. I have been doing some WS-* work and having some code to look at has been great.

**Comment by ebeigarts** [comment]
I updated travis yml in master to run against newer ruby versions, and the tests failed, don't know why the tests didn't fail previously, maybe this is due to some older dependencies (nokogiri maybe). Thanks.

**Comment by mrezentes** [comment]
Great. Thank you.

**Pull request merged**
